config_updater:
  maps:
    prow/config/config.yaml:
      name: config
    prow/config/plugins.yaml:
      name: plugins
    prow/config/external_plugins_config.yaml:
      name: external-plugins-config
    prow/config/labels.yaml:
      name: labels-config

welcome:
  - repos:
      - ti-community-infra
    message_template: "Welcome @{{.AuthorLogin}}! <br><br>It looks like this is your first PR to <a href='https://github.com/{{.Org}}/{{.Repo}}'>{{.Org}}/{{.Repo}}</a> ðŸŽ‰. <br><br>You will be prompted by a bot to use commands during the review process. Do not be afraid to follow the prompts! It is okay to experiment. [Here is the bot commands documentation](https://prow.tidb.io/command-help). <br><br>You can also check if {{.Org}}/{{.Repo}} has [its own contribution guidelines](https://github.com/{{.Org}}/{{.Repo}}/tree/master/CONTRIBUTING.md). <br><br>We want to make sure your contribution gets all the attention it needs! <br><br>Thank you, and welcome to tidb community. :smiley:"

size:
  s: 10
  m: 30
  l: 90
  xl: 270
  xxl: 520

require_matching_label:
  - missing_label: needs-type
    org: ti-community-infra
    repo: ti-community-prow
    issues: true
    regexp: ^type/
    missing_comment: |
      There are no type labels on this issue. Please add an appropriate label by using the following command:
      - `/type <type-name>`
  - missing_label: needs-type
    org: tikv
    repo: pd
    issues: true
    regexp: ^type/
    missing_comment: |
      There are no type labels on this issue. Please add an appropriate label by using the following command:
      - `/type <type-name>`

triggers:
  - repos:
      - ti-community-infra/configs
      - ti-community-infra/ti-community-prow

repo_milestone:
  ti-community-infra/ti-community-prow:
    maintainers_id: 4300209
    maintainers_team: bots-maintainers
    maintainers_friendly_name: Robots Maintainers

milestone_applier:
  ti-community-infra/ti-community-prow:
    master: v0.16.6

plugins:
  ti-community-infra/test-live:
    - assign
    - branchcleaner
    - size
    - welcome
    - wip
    - lifecycle
    - help
    - hold
  ti-community-infra/ti-challenge-bot:
    - assign
    - branchcleaner
    - size
    - welcome
    - wip
    - lifecycle
    - help
    - hold
  ti-community-infra/ti-community-bot:
    - assign
    - branchcleaner
    - size
    - welcome
    - wip
    - lifecycle
    - help
    - hold
  ti-community-infra/ti-community-prow:
    - assign
    - branchcleaner
    - size
    - welcome
    - wip
    - lifecycle
    - help
    - hold
    - require-matching-label
    - trigger
    - milestone
    - milestoneapplier
  ti-community-infra/configs:
    - assign
    - branchcleaner
    - size
    - welcome
    - wip
    - lifecycle
    - help
    - hold
    - config-updater
    - require-matching-label
    - trigger
  tikv/community:
    - assign
    - hold
    - wip
    - lifecycle
  tikv/pd:
    - assign
    - require-matching-label
    - hold
    - wip
  pingcap/community:
    - assign
    - hold
    - wip
    - lifecycle
  pingcap/tidb-dashboard:
    - assign
  pingcap/tidb-operator:
    - assign
  pingcap/tiup:
    - assign
    - hold
    - wip
    - size
    - lifecycle

external_plugins:
  ti-community-infra/test-live:
    - name: ti-community-lgtm
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request_review
    - name: ti-community-merge
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request
    - name: ti-community-tars
      events:
        - pull_request
        - issue_comment
  ti-community-infra/ti-community-prow:
    - name: ti-community-lgtm
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request_review
    - name: ti-community-merge
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request
    - name: ti-community-label
      events:
        - issue_comment
    - name: ti-community-autoresponder
      events:
        - issue_comment
        - pull_request_review_comment
    - name: needs-rebase
      events:
        - pull_request
        - issue_comment
    - name: ti-community-blunderbuss
      events:
        - pull_request
        - issue_comment
  ti-community-infra/configs:
    - name: ti-community-lgtm
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request_review
    - name: ti-community-merge
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request
    - name: ti-community-label
      events:
        - issue_comment
    - name: ti-community-autoresponder
      events:
        - issue_comment
        - pull_request_review_comment
    - name: needs-rebase
      events:
        - pull_request
        - issue_comment
    - name: ti-community-blunderbuss
      events:
        - pull_request
        - issue_comment
    - name: ti-community-tars
      events:
        - pull_request
        - issue_comment
  ti-community-infra/ti-community-bot:
    - name: ti-community-lgtm
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request_review
    - name: ti-community-merge
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request
    - name: ti-community-label
      events:
        - issue_comment
    - name: needs-rebase
      events:
        - pull_request
        - issue_comment
    - name: ti-community-blunderbuss
      events:
        - pull_request
        - issue_comment
    - name: ti-community-tars
      events:
        - pull_request
        - issue_comment
  ti-community-infra/ti-challenge-bot:
    - name: ti-community-lgtm
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request_review
    - name: ti-community-merge
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request
    - name: ti-community-label
      events:
        - issue_comment
    - name: needs-rebase
      events:
        - pull_request
        - issue_comment
    - name: ti-community-blunderbuss
      events:
        - pull_request
        - issue_comment
    - name: ti-community-tars
      events:
        - pull_request
        - issue_comment
  tikv/community:
    - name: ti-community-lgtm
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request_review
    - name: ti-community-merge
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request
    - name: needs-rebase
      events:
        - pull_request
        - issue_comment
    - name: ti-community-blunderbuss
      events:
        - pull_request
        - issue_comment
  tikv/pd:
    - name: ti-community-lgtm
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request_review
    - name: ti-community-merge
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request
    - name: needs-rebase
      events:
        - pull_request
        - issue_comment
    - name: ti-community-autoresponder
      events:
        - issue_comment
        - pull_request_review_comment
    - name: ti-community-blunderbuss
      events:
        - pull_request
        - issue_comment
    - name: ti-community-tars
      events:
        - pull_request
        - issue_comment
    - name: ti-community-label
      events:
        - issue_comment
  pingcap/tidb-dashboard:
    - name: ti-community-lgtm
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request_review
    - name: ti-community-merge
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request
    - name: needs-rebase
      events:
        - pull_request
        - issue_comment
  pingcap/community:
    - name: ti-community-lgtm
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request_review
    - name: ti-community-merge
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request
    - name: needs-rebase
      events:
        - pull_request
        - issue_comment
    - name: ti-community-blunderbuss
      events:
        - pull_request
        - issue_comment
  pingcap/tidb-operator:
    - name: ti-community-lgtm
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request_review
    - name: ti-community-merge
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request
    - name: needs-rebase
      events:
        - pull_request
        - issue_comment
    - name: ti-community-blunderbuss
      events:
        - pull_request
        - issue_comment
    - name: ti-community-tars
      events:
        - pull_request
        - issue_comment
  pingcap/tiup:
    - name: ti-community-lgtm
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request_review
    - name: ti-community-merge
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request
    - name: needs-rebase
      events:
        - pull_request
        - issue_comment
    - name: ti-community-blunderbuss
      events:
        - pull_request
        - issue_comment
    - name: ti-community-tars
      events:
        - pull_request
        - issue_comment
    - name: ti-community-label
      events:
        - issue_comment
